module.exports = {
  CALL_CREATED: "CALL_CREATED",
  CALL_DROPPED: "CALL_DROPPED",
  CALL_PICKED: "CALL_PICKED",
  CALL_QUEUED: "CALL_QUEUED",
  CALL_CONNECTED: "CALL_CONNECTED",
  CALL_COMPLETED: "CALL_COMPLETED",

  AGENT_ASSIGNED: "AGENT_ASSIGNED",
  AGENT_AVAILABLE: "AGENT_AVAILABLE"
};
